/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID cad4)
#  Generated on:      Wed Nov  8 16:45:33 2023
#  Design:            top
#  Command:           saveNetlist top_route.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Nov  8 2023 16:14:13 IST (Nov  8 2023 10:44:13 UTC)
// Verification Directory fv/top 
module top (
	a, 
	b, 
	clk, 
	rst, 
	mac_out);
   input [3:0] a;
   input [3:0] b;
   input clk;
   input rst;
   output [7:0] mac_out;

   // Internal wires
   wire FE_DBTN1_n_15;
   wire FE_DBTN0_n_100;
   wire [7:0] mac_out_temp;
   wire [3:0] ain;
   wire [3:0] bin;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire n_7;
   wire n_10;
   wire n_11;
   wire n_13;
   wire n_15;
   wire n_19;
   wire n_22;
   wire n_24;
   wire n_25;
   wire n_27;
   wire n_28;
   wire n_31;
   wire n_32;
   wire n_34;
   wire n_39;
   wire n_40;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_47;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_81;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_117;
   wire n_119;
   wire n_120;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_144;
   wire n_145;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_186;
   wire n_200;
   wire n_206;
   wire n_211;
   wire n_212;
   wire n_213;
   wire n_214;
   wire n_233;
   wire n_234;
   wire n_238;
   wire n_240;
   wire n_244;
   wire n_245;
   wire n_247;
   wire n_254;
   wire n_255;
   wire n_257;
   wire n_258;

   XNOR2X1 FE_RC_0_0 (.A(n_162),
	.B(n_156),
	.Y(n_166));
   CLKINVX1 FE_DBTC1_n_15 (.A(n_15),
	.Y(FE_DBTN1_n_15));
   CLKINVX1 FE_DBTC0_n_100 (.A(n_100),
	.Y(FE_DBTN0_n_100));
   DFFRX1 \p03_ain_reg[7]  (.CK(clk),
	.D(n_166),
	.Q(mac_out[7]),
	.QN(mac_out_temp[7]),
	.RN(n_165));
   DFFRHQX1 \p03_ain_reg[6]  (.CK(clk),
	.D(n_164),
	.Q(mac_out[6]),
	.RN(n_165));
   MXI2XL g10450__5107 (.A(n_240),
	.B(n_157),
	.S0(n_161),
	.Y(n_164));
   DFFRHQX1 \p03_ain_reg[5]  (.CK(clk),
	.D(n_160),
	.Q(mac_out[5]),
	.RN(n_165));
   AOI21X1 g10449__6260 (.A0(n_161),
	.A1(n_157),
	.B0(n_155),
	.Y(n_162));
   MXI2XL g10456__4319 (.A(n_154),
	.B(n_145),
	.S0(n_142),
	.Y(n_160));
   MXI2XL g10457__8428 (.A(n_234),
	.B(n_233),
	.S0(mac_out_temp[7]),
	.Y(n_156));
   OAI21X1 g10454__5526 (.A0(n_142),
	.A1(n_145),
	.B0(n_144),
	.Y(n_157));
   NOR2BX1 g10458__6783 (.AN(mac_out[6]),
	.B(n_152),
	.Y(n_155));
   CLKINVX1 g10460 (.A(n_145),
	.Y(n_154));
   MXI2XL g10464__3680 (.A(n_150),
	.B(n_151),
	.S0(n_131),
	.Y(n_152));
   MXI2XL g10465__1617 (.A(n_151),
	.B(n_150),
	.S0(n_133),
	.Y(n_161));
   INVXL g10466 (.A(n_148),
	.Y(n_149));
   NAND2XL g10467__2802 (.A(mac_out[5]),
	.B(n_141),
	.Y(n_144));
   AOI21X1 g10463__1705 (.A0(n_126),
	.A1(n_258),
	.B0(n_244),
	.Y(n_145));
   MXI2XL g10475__5122 (.A(n_134),
	.B(n_138),
	.S0(mac_out[4]),
	.Y(n_148));
   CLKINVX1 g10469 (.A(n_151),
	.Y(n_150));
   MXI2XL g10474__7098 (.A(n_139),
	.B(n_140),
	.S0(n_255),
	.Y(n_141));
   MXI2XL g10470__6131 (.A(n_140),
	.B(n_139),
	.S0(n_123),
	.Y(n_142));
   CLKINVX1 g10479 (.A(n_134),
	.Y(n_138));
   AOI2BB2X1 g10472__1881 (.A0N(n_254),
	.A1N(n_120),
	.B0(n_122),
	.B1(n_139),
	.Y(n_151));
   MXI2XL g10489__4733 (.A(n_130),
	.B(n_132),
	.S0(n_213),
	.Y(n_133));
   MXI2XL g10490__6161 (.A(n_130),
	.B(n_132),
	.S0(n_129),
	.Y(n_131));
   NOR2BX1 g10481__9315 (.AN(n_128),
	.B(n_124),
	.Y(n_134));
   CLKINVX1 g10473 (.A(n_126),
	.Y(n_127));
   CLKINVX1 g10482 (.A(n_139),
	.Y(n_140));
   CLKINVX1 g10485 (.A(n_124),
	.Y(n_125));
   OAI21X1 g10483__9945 (.A0(n_206),
	.A1(n_108),
	.B0(n_110),
	.Y(n_139));
   XNOR3X1 g10488__2883 (.A(mac_out[5]),
	.B(n_212),
	.C(FE_DBTN0_n_100),
	.Y(n_123));
   NAND2XL g10491__2346 (.A(n_120),
	.B(n_254),
	.Y(n_122));
   OAI21X1 g10476__1666 (.A0(n_119),
	.A1(n_113),
	.B0(n_112),
	.Y(n_126));
   NAND2BX1 g10484__7410 (.AN(n_206),
	.B(n_117),
	.Y(n_128));
   NOR2BX1 g10486__6417 (.AN(n_206),
	.B(n_117),
	.Y(n_124));
   CLKINVX1 g10500 (.A(n_130),
	.Y(n_132));
   CLKINVX1 g10487 (.A(n_113),
	.Y(n_114));
   OAI21X1 g10499__2398 (.A0(n_104),
	.A1(n_97),
	.B0(mac_out[3]),
	.Y(n_112));
   MXI2XL g10501__5107 (.A(n_100),
	.B(FE_DBTN0_n_100),
	.S0(n_77),
	.Y(n_120));
   AOI21X1 g10503__6260 (.A0(n_57),
	.A1(FE_DBTN0_n_100),
	.B0(n_58),
	.Y(n_130));
   MXI2XL g10494__4319 (.A(n_98),
	.B(n_102),
	.S0(n_109),
	.Y(n_117));
   XNOR3X1 g10496__8428 (.A(n_103),
	.B(mac_out[3]),
	.C(n_91),
	.Y(n_113));
   NAND2XL g10497__5526 (.A(n_109),
	.B(n_98),
	.Y(n_110));
   NOR2XL g10498__6783 (.A(n_109),
	.B(n_98),
	.Y(n_108));
   NOR2XL g10517__3680 (.A(n_103),
	.B(n_94),
	.Y(n_104));
   DFFRHQX1 \p03_ain_reg[2]  (.CK(clk),
	.D(n_93),
	.Q(mac_out[2]),
	.RN(n_165));
   INVXL g10493 (.A(n_119),
	.Y(n_99));
   CLKINVX1 g10505 (.A(n_98),
	.Y(n_102));
   NOR2BXL g10515__1617 (.AN(n_103),
	.B(n_91),
	.Y(n_97));
   OAI21X1 g10514__1705 (.A0(n_83),
	.A1(n_95),
	.B0(n_92),
	.Y(n_100));
   INVXL g10521 (.A(n_91),
	.Y(n_94));
   NOR2XL g10516__5122 (.A(n_103),
	.B(n_91),
	.Y(n_98));
   OAI21XL g10506__8246 (.A0(n_88),
	.A1(n_87),
	.B0(n_89),
	.Y(n_93));
   AOI21X1 g10495__7098 (.A0(mac_out[2]),
	.A1(n_211),
	.B0(n_86),
	.Y(n_119));
   OAI21X1 g10518__6131 (.A0(n_84),
	.A1(n_85),
	.B0(n_75),
	.Y(n_92));
   MXI2XL g10523__1881 (.A(n_66),
	.B(n_76),
	.S0(n_72),
	.Y(n_91));
   NAND2XL g10507__5115 (.A(n_88),
	.B(n_87),
	.Y(n_89));
   NOR2BX1 g10508__7482 (.AN(n_87),
	.B(n_88),
	.Y(n_86));
   NOR2XL g10520__4733 (.A(n_74),
	.B(n_85),
	.Y(n_95));
   NAND2XL g10529__6161 (.A(n_83),
	.B(n_73),
	.Y(n_84));
   XNOR3XL g10524__9315 (.A(n_79),
	.B(mac_out[2]),
	.C(n_78),
	.Y(n_87));
   DFFRHQX1 \p03_ain_reg[1]  (.CK(clk),
	.D(n_69),
	.Q(mac_out[1]),
	.RN(n_165));
   AOI21X1 g10526__2346 (.A0(n_214),
	.A1(n_62),
	.B0(n_76),
	.Y(n_85));
   MXI2XL g10539__1666 (.A(n_71),
	.B(n_186),
	.S0(n_44),
	.Y(n_75));
   CLKINVX1 g10532 (.A(n_73),
	.Y(n_74));
   MXI2XL g10541__7410 (.A(n_59),
	.B(n_60),
	.S0(n_61),
	.Y(n_72));
   OAI22XL g10540__6417 (.A0(n_71),
	.A1(n_50),
	.B0(n_51),
	.B1(n_186),
	.Y(n_81));
   XOR2XL g10533__5477 (.A(n_68),
	.B(n_67),
	.Y(n_69));
   AOI22X1 g10527__2398 (.A0(n_68),
	.A1(n_67),
	.B0(mac_out[1]),
	.B1(n_56),
	.Y(n_88));
   CLKINVX1 g10528 (.A(n_76),
	.Y(n_66));
   NAND2XL g10534__5107 (.A(n_64),
	.B(n_63),
	.Y(n_73));
   NAND2BX1 g10537__4319 (.AN(n_79),
	.B(n_78),
	.Y(n_76));
   NAND2BX1 g10542__8428 (.AN(n_62),
	.B(n_55),
	.Y(n_64));
   AOI21XL g10536__5526 (.A0(n_62),
	.A1(n_61),
	.B0(n_214),
	.Y(n_63));
   CLKINVX1 g10549 (.A(n_59),
	.Y(n_60));
   CLKXOR2X1 g10544__6783 (.A(n_58),
	.B(n_57),
	.Y(n_77));
   MXI2XL g10551__3680 (.A(n_245),
	.B(n_47),
	.S0(n_39),
	.Y(n_59));
   OAI21X1 g10543__1617 (.A0(n_52),
	.A1(n_53),
	.B0(n_54),
	.Y(n_78));
   MXI2XL g10552__2802 (.A(n_45),
	.B(n_56),
	.S0(mac_out[1]),
	.Y(n_67));
   NAND2BX1 g10553__1705 (.AN(n_49),
	.B(n_57),
	.Y(n_71));
   CLKINVX1 g10545 (.A(n_61),
	.Y(n_55));
   NAND2XL g10546__5122 (.A(n_53),
	.B(n_52),
	.Y(n_54));
   CLKINVX1 g10561 (.A(n_50),
	.Y(n_51));
   NAND2XL g10554__8246 (.A(FE_DBTN1_n_15),
	.B(n_43),
	.Y(n_57));
   NOR2XL g10548__7098 (.A(n_238),
	.B(n_49),
	.Y(n_61));
   CLKINVX1 g10562 (.A(n_45),
	.Y(n_56));
   XNOR2X1 g10563__6131 (.A(n_44),
	.B(n_83),
	.Y(n_50));
   AOI21X1 g10557__1881 (.A0(n_13),
	.A1(n_40),
	.B0(n_22),
	.Y(n_43));
   AOI21X1 g10558__5115 (.A0(n_32),
	.A1(n_31),
	.B0(n_68),
	.Y(n_42));
   AOI22X1 g10559__7482 (.A0(n_15),
	.A1(n_247),
	.B0(n_214),
	.B1(FE_DBTN1_n_15),
	.Y(n_47));
   NAND2XL g10564__4733 (.A(n_25),
	.B(n_34),
	.Y(n_52));
   MXI2XL g10566__6161 (.A(n_27),
	.B(n_28),
	.S0(n_40),
	.Y(n_45));
   AOI22X1 g10560__9315 (.A0(n_19),
	.A1(n_15),
	.B0(n_39),
	.B1(FE_DBTN1_n_15),
	.Y(n_62));
   NAND2XL g10573__9945 (.A(n_7),
	.B(n_11),
	.Y(n_53));
   NAND2XL g10567__2346 (.A(n_200),
	.B(n_10),
	.Y(n_34));
   NOR2XL g10568__7410 (.A(n_24),
	.B(n_200),
	.Y(n_49));
   NAND2XL g10583__6417 (.A(ain[2]),
	.B(bin[2]),
	.Y(n_83));
   NOR2XL g10569__5477 (.A(n_32),
	.B(n_31),
	.Y(n_68));
   INVXL g10574 (.A(n_27),
	.Y(n_28));
   NAND2XL g10571__2398 (.A(n_24),
	.B(n_11),
	.Y(n_25));
   AND2X1 g10599__5107 (.A(bin[1]),
	.B(ain[3]),
	.Y(n_109));
   OAI21X1 g10572__6260 (.A0(bin[0]),
	.A1(bin[2]),
	.B0(ain[1]),
	.Y(n_22));
   CLKINVX1 g10592 (.A(n_39),
	.Y(n_19));
   NAND2XL g10598__4319 (.A(ain[0]),
	.B(bin[1]),
	.Y(n_40));
   NAND2XL g10579__8428 (.A(ain[2]),
	.B(bin[3]),
	.Y(n_58));
   NAND2XL g10597__5526 (.A(ain[2]),
	.B(bin[0]),
	.Y(n_79));
   CLKINVX1 g10576 (.A(n_24),
	.Y(n_10));
   NAND2XL g10582__3680 (.A(ain[1]),
	.B(bin[3]),
	.Y(n_44));
   INVXL g10575 (.A(n_7),
	.Y(n_31));
   NAND2XL g10577__1617 (.A(ain[1]),
	.B(bin[0]),
	.Y(n_27));
   NAND2XL g10603__2802 (.A(ain[1]),
	.B(bin[2]),
	.Y(n_39));
   AND2X1 g10602__1705 (.A(ain[1]),
	.B(bin[1]),
	.Y(n_11));
   INVXL g10609 (.A(bin[2]),
	.Y(n_13));
   NAND2XL g10580__5122 (.A(bin[0]),
	.B(ain[3]),
	.Y(n_103));
   AND2X1 g10578__8246 (.A(bin[0]),
	.B(ain[0]),
	.Y(n_7));
   NAND2XL g10604__7098 (.A(bin[3]),
	.B(ain[0]),
	.Y(n_15));
   NAND2XL g10584__6131 (.A(bin[3]),
	.B(ain[3]),
	.Y(n_129));
   NAND2XL g10581__1881 (.A(ain[0]),
	.B(bin[2]),
	.Y(n_24));
   DFFRHQX1 \p02_ain_reg[2]  (.CK(clk),
	.D(b[2]),
	.Q(bin[2]),
	.RN(n_165));
   DFFRHQX1 \p01_ain_reg[3]  (.CK(clk),
	.D(a[3]),
	.Q(ain[3]),
	.RN(n_165));
   DFFRHQX1 \p01_ain_reg[0]  (.CK(clk),
	.D(a[0]),
	.Q(ain[0]),
	.RN(n_165));
   DFFRHQX1 \p02_ain_reg[0]  (.CK(clk),
	.D(b[0]),
	.Q(bin[0]),
	.RN(n_165));
   DFFRHQX1 \p01_ain_reg[2]  (.CK(clk),
	.D(a[2]),
	.Q(ain[2]),
	.RN(n_165));
   DFFRHQX1 \p01_ain_reg[1]  (.CK(clk),
	.D(a[1]),
	.Q(ain[1]),
	.RN(n_165));
   DFFRHQX1 \p02_ain_reg[1]  (.CK(clk),
	.D(b[1]),
	.Q(bin[1]),
	.RN(n_165));
   INVXL g10625 (.A(rst),
	.Y(n_165));
   INVXL fopt10648 (.A(n_71),
	.Y(n_186));
   CLKINVX1 fopt10655 (.A(n_11),
	.Y(n_200));
   CLKXOR2X1 g2 (.A(n_81),
	.B(n_95),
	.Y(n_206));
   XNOR2XL g10660 (.A(n_79),
	.B(n_78),
	.Y(n_211));
   CLKXOR2X1 g10661 (.A(n_254),
	.B(n_77),
	.Y(n_212));
   CLKXOR2X1 g10662 (.A(mac_out[6]),
	.B(n_129),
	.Y(n_213));
   NAND2XL g10663 (.A(ain[2]),
	.B(bin[1]),
	.Y(n_214));
   DFFRHQX1 \p02_ain_reg[3]  (.CK(clk),
	.D(b[3]),
	.Q(bin[3]),
	.RN(n_165));
   AO21X1 g10686 (.A0(n_132),
	.A1(n_151),
	.B0(n_129),
	.Y(n_233));
   AOI21XL g10462__10687 (.A0(n_132),
	.A1(n_151),
	.B0(n_129),
	.Y(n_234));
   CLKINVX1 fopt10690 (.A(n_53),
	.Y(n_238));
   INVXL fopt10692 (.A(n_157),
	.Y(n_240));
   NOR2BX1 g10695 (.AN(mac_out[4]),
	.B(n_134),
	.Y(n_244));
   CLKINVX1 fopt (.A(n_47),
	.Y(n_245));
   AND2X1 g10696 (.A(ain[2]),
	.B(bin[1]),
	.Y(n_247));
   DFFRX1 \p03_ain_reg[0]  (.CK(clk),
	.D(n_42),
	.Q(mac_out[0]),
	.QN(n_32),
	.RN(n_165));
   NAND2BX1 g10703 (.AN(n_13),
	.B(ain[3]),
	.Y(n_254));
   XNOR2X1 g10704 (.A(FE_DBTN0_n_100),
	.B(n_212),
	.Y(n_255));
   NAND2BX1 g8 (.AN(n_257),
	.B(n_125),
	.Y(n_258));
   NAND2BXL g9 (.AN(mac_out[4]),
	.B(n_128),
	.Y(n_257));
   SDFFRX1 \p03_ain_reg[4]  (.CK(clk),
	.D(n_149),
	.Q(mac_out[4]),
	.QN(UNCONNECTED),
	.RN(n_165),
	.SE(n_127),
	.SI(n_148));
   SDFFRX1 \p03_ain_reg[3]  (.CK(clk),
	.D(n_99),
	.Q(mac_out[3]),
	.QN(UNCONNECTED0),
	.RN(n_165),
	.SE(n_114),
	.SI(n_119));
endmodule

